apiVersion: v1
kind: Service
metadata:
  name: dbeaver-service
  namespace: dbeaver
spec:
  type: NodePort
  selector:
    app: dbeaver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8978
      nodePort: 30078
