apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyuubi
  namespace: kyuubi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyuubi
  template:
    metadata:
      labels:
        app: kyuubi
    spec:
      containers:
        - name: kyuubi
          image: my-custom-kyuubi:1.8.3
          imagePullPolicy: Never
          ports:
            - containerPort: 10009
          env:
            - name: SPARK_HOME
              value: "/opt/kyuubi/externals/spark-3.4.2-bin-hadoop3"
            - name: HADOOP_CONF_DIR
              value: "/etc/hadoop/conf"
            - name: SPARK_KUBERNETES_CONTAINER_IMAGE
              value: "my-local-spark:3.4.2"
            - name: KYUUBI_SESSION_ENGINE_TIMEOUT
              value: "360000"
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "1"
              memory: "4Gi"
