apiVersion: v1
kind: Service
metadata:
  name: kyuubi-service
  namespace: kyuubi
spec:
  selector:
    app: kyuubi
  ports:
    - protocol: TCP
      port: 10009
      targetPort: 10009
      nodePort: 30009
  type: NodePort
