apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyuubi-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyuubi-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kyuubi
roleRef:
  kind: ClusterRole
  name: kyuubi-role
  apiGroup: rbac.authorization.k8s.io
