apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyuubi-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps", "pods", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "deletecollection"]
