apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyuubi-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kyuubi
roleRef:
  kind: Role
  name: kyuubi-role
  apiGroup: rbac.authorization.k8s.io
