apiVersion: v1
kind: Service
metadata:
  name: kyuubi-service
  namespace: kyuubi
spec:
  selector:
    app: kyuubi
  ports:
    - name: jdbc
      protocol: TCP
      port: 10009  # JDBC Port
      targetPort: 10009
      nodePort: 30009
    - name: web-ui
      protocol: TCP
      port: 10099  # Web UI Port
      targetPort: 10099
      nodePort: 30099
  type: NodePort
