apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: [ "sh", "-c", "echo 'Hello from emptyDir' > /cache/data.txt && sleep 3600" ]
      volumeMounts:
        - name: cache-volume
          mountPath: /cache  # Mounting emptyDir at /cache
  volumes:
    - name: cache-volume
      emptyDir: {}  # Temporary storage
