apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo
spec:
  volumes:
    - name: my-pvc-volume
      persistentVolumeClaim:
        claimName: my-pvc  # Referencing the PVC we created earlier
  containers:
    - name: busybox-container
      image: busybox
      command: [ "sh", "-c", "echo 'Hello from PVC' > /data/pvc.txt && sleep 3600" ]
      volumeMounts:
        - name: my-pvc-volume
          mountPath: /data  # Mounting PVC to /data
