image: python:3.10


stages:
  - test
  - deploy

test_connectivity:
  stage: test
  script:
    - echo "Testing connectivity to Snowflake..."
    - curl -Iv https://ZKZNAHE-UE29963.snowflakecomputing.com


deploy_schema:
  stage: deploy
  script:
    - pip install -r snowflake-iac/requirements.txt
    - python snowflake-iac/scripts/deploy.py
  when: manual
