image: python:3.10

test_connectivity:
  script:
    - echo "Testing connectivity to Snowflake..."
    - curl -Iv https://ZKZNAHE-UE29963.snowflakecomputing.com

stages:
  - deploy

deploy_schema:
  stage: deploy
  script:
    - pip install -r snowflake-iac/requirements.txt
    - python snowflake-iac/scripts/deploy.py
  when: manual
