image: python:3.10


stages:
  - test
  - deploy

test_connectivity:
  stage: test
  script:
    - echo "Testing connectivity to Snowflake..."
    - curl -Iv https://$SNOWFLAKE_ACCOUNT.snowflakecomputing.com


deploy_schema:
  stage: deploy
  needs: [test_connectivity]
  script:
    - pip install -r snowflake-iac/requirements.txt
    - python snowflake-iac/scripts/deploy.py
  when: manual
